version: '3.7'

services:
  cere-block-scanner-service:
    build:
      context: ./
    container_name: cere-block-scanner-service
    restart: always
    ports:
      - 2015:2015
    logging:
      driver: json-file
    environment:
      - DB_HOST=cere-block-scanner-db
      - DB_USERNAME=block-scanner-service
      - DB_PASSWORD=block-scanner-service
      - DB_DATABASE=block-scanner-service
      - DB_PORT=5432
      - DB_SYNCHRONIZE=true
      - DB_LOGGING=true
      - DB_ENTITIES=**/*.entity.js
      - DB_CONNECTION_ALIVE=false
      - LOG_LEVEL=debug
      - NETWORK_WS_URL=wss://testnet-node-1.cere.network:9945
      - MAX_BALANCE=1
      - NUMBER_OF_TOKENS_TO_SEND=1000000000000000000
      - REQUEST_PER_DAY=100
      - REQUEST_PER_IP_PER_DAY=3

    depends_on:
      - cere-block-scanner-db

  cere-block-scanner-db:
    image: postgres:9-alpine
    container_name: cere-block-scanner-db
    environment:
      POSTGRES_USER: block-scanner-service
      POSTGRES_PASSWORD: block-scanner-service
      POSTGRES_DB: block-scanner-service
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata-block-scanner/:/var/lib/postgresql/data/pgdata
    logging:
      driver: none
