name: Release to stage
on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

jobs:
  build_laboratory_api:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/build-and-push-docker.yaml@master
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      org: cerebellumnetwork
      environment: stage
      image: crb-${{ github.event.repository.name }}
      repository: crb-${{ github.event.repository.name }}
      file: ./apps/api/Dockerfile
    secrets: inherit

  build_laboratory_fetcher:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/build-and-push-docker.yaml@master
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      org: cerebellumnetwork
      environment: stage
      image: crb-laboratory-fetcher
      repository: crb-laboratory-fetcher
      file: ./apps/fetcher/Dockerfile
    secrets: inherit

  deploy_laboratory_api:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-with-helm.yaml@master
    needs: build_laboratory_api
    with:
      runs-on: '["self-hosted", "cere-network-stg-deployer"]'
      helm-repo-path: laboratory/laboratory-api
      helm-release: laboratory-api
      namespace: laboratory
      tag: ${{ needs.build_laboratory_api.outputs.version }}
      environment: stage
    secrets: inherit

  deploy_laboratory_fetcher:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-with-helm.yaml@master
    needs: build_laboratory_fetcher
    with:
      runs-on: '["self-hosted", "cere-network-stg-deployer"]'
      helm-repo-path: laboratory/laboratory-fetcher
      helm-release: laboratory-fetcher
      namespace: laboratory
      tag: ${{ needs.build_laboratory_fetcher.outputs.version }}
      environment: stage
    secrets: inherit
